const tokens = [
	{
		id: 'BTC',
		image: '/images/token/bitcoin.svg',
		name: 'Bitcoin',
		price: '36376.81',
		profit: '-8.92',
		balance: '0 BTC',
	},
	{
		id: 'ETH',
		image: '/images/token/ethereum.svg',
		name: 'Ethereum',
		price: '2593.08',
		profit: '+11.24',
		balance: '0.3708 ETH',
	},
	{
		id: 'BNB',
		image: '/images/token/bnb.svg',
		name: 'BNB',
		price: '386.59',
		profit: '-9.68',
		balance: '0 BNB',
	},
	{
		id: 'USDT',
		image: '/images/token/tether.svg',
		name: 'Tether USD',
		price: '1.00',
		profit: '+10.02',
		balance: '0 USDT',
	},
	{
		id: 'XRP',
		image: '/images/token/ripple.svg',
		name: 'XRP Ripple',
		price: '0.64',
		profit: '-11.49',
		balance: '0 XRP',
	},
	{
		id: 'TRX',
		image: '/images/token/tron.svg',
		name: 'Tron',
		price: '0.06',
		profit: '-9.65',
		balance: '0 TRX',
	},
	{
		id: 'LINK',
		image: '/images/token/chainlink.svg',
		name: 'LINK',
		price: '17.53',
		profit: '-11.91',
		balance: '0 LINK',
	},
];

export default tokens;
